### ISSUE TITLE
Hooks not re-exported?

### ISSUE THREAD

**Issue by JeffBaumgardt** [dittowords/ditto-react#16]
I was going to start using hooks vs jsx components for tokens but the hooks are not exposed via the main module export. For now I have to use `import {useDitto} from 'ditto-react/dist/hooks/useDitto'` it's a little verbose and the named export is also a bit wonky here.

Are the hooks still considered in development here and thus not yet officially supported? Is there anything I can do to help document and support hooks?

**Comment by JeffBaumgardt** [comment]
Actually I take part back. You can't actually import from dist as that is only the typings, not the actual code. So the hooks are not exported, or importable at the moment.

The reason for this is there might be times where I only want the text and not a component, that is wrapping the text.

There is quite a difference between `React.createElement` and `String`.

**Comment by JeffBaumgardt** [comment]
This kind of leans into #15 as a solution.

**Comment by azjgard** [comment]
Hi @JeffBaumgardt, thanks for opening this! Agreed that #15 is definitely aiming to solve the problem you've identified, and  #13 basically boils down to this same issue as well.

A public hooks-based API for library consumers to use has been on our roadmap for quite some time, but we haven't yet gotten around to implementing it. The hooks that `ditto-react` uses internally have some ergonomic rough edges due to how they've evolved from legacy constraints, which is why those haven't always been exported alongside the associated React components.

Although we still expect to release a better-designed hooks API in the future, I think it makes total sense to allow usage of the existing (currently internal) hooks until then -- as mentioned in [this comment](https://github.com/dittowords/ditto-react/issues/13#issuecomment-1125473866), we just want to make sure we get things right before advocating for people to adopt them.

**Comment by azjgard** [comment]
I'm going to close this and consolidate it into #15 according to what I outlined in [this comment](https://github.com/dittowords/ditto-react/pull/15#issuecomment-1239967622).

Thanks again @JeffBaumgardt, feel free to follow-up in the PR thread with anything else related to this!
